"""add room and meeting status

Revision ID: d73657f093ef
Revises: 625458dd1b07
Create Date: 2026-06-19 05:09:13.976315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73657f093ef'
down_revision: Union[str, Sequence[str], None] = '625458dd1b07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('is_completed', sa.Boolean(), nullable=False))
    op.add_column('rooms', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'is_active')
    op.drop_column('meetings', 'is_completed')
    # ### end Alembic commands ###
